### PR TITLE
Fix "unary operator expected"

### PR DESCRIPTION
**Pull request by wtanaka**
Per "man ["

       STRING1 = STRING2
              the strings are equal

### CODE REVIEW

**Comment by neillturner** [comment]
No sure about this change. don't we just need to change 
config[:test_serverspec_installed] ? "if [ $(#{sudo('gem')} list serverspec -i) = 'false' ]; then" : nil
to
config[:test_serverspec_installed] ? "if [ \"$(#{sudo('gem')} list serverspec -i)|" = \"false\" ]; then" : nil

**Comment by wtanaka** [comment]
I think it's necessary to switch == to =, but it doesn't seem to be sufficient.  There seems like there might be two other issues, but I'm not 100% sure:

1. sudo('gem') isn't outputting the string "gem" in some circumstances
2. there isn't support for running bundler (specifically) without root, while still retaining root for other things that need it, and CircleCI doesn't seem to work out of the box with that.

**Comment by wtanaka** [comment]
I don't know Ruby very well; I looked through http://ruby-doc.org/core-2.4.0/doc/syntax/literals_rdoc.html to see if I could understand what the intention of the `|` character is; the example you gave doesn't seem to parse into a full expression:

```
                                                             Is this your suggested change?
                                                                |
                                                                v
irb(main):007:1> x = "if [ "$(#{sudo('gem')} list serverspec -i)|" = "false" ]; then"
irb(main):008:2* 
```

**Comment by neillturner** [comment]
I enhanced the error handling in version 0..6.4
You problem is in ruby not being installed correctly hence the gem command doesn't work. 
you could try setting sudo to false

**Pull request closed without merging**
